apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qa-guardian
  namespace: qa-guardian
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: qa-guardian-andres.pages.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
